image: ---

variables:
  DOCKER_HOST: ---
  DOCKER_DRIVER: overlay2
  NODE_ENV: production

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - touch ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  - ssh-keyscan --- > ~/.ssh/known_hosts
  - echo "$SSH_KEY" | tr -d '\r' | ssh-add -
  - echo "$SSH_KEY" | tr -d '\r' > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - echo $SSH_KEY | tr -d '\r'
    - ssh -v -i ~/.ssh/id_rsa deploy@---- "cd /srv/rs2 && git checkout master && git pull origin master && docker-compose up -d && exit"
  when: manual
  only:
    - master